'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServicioDatos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://localhost/", ConfigurationName:="ServicioDatos.empleadosSoap")>  _
    Public Interface empleadosSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/BuscaRegistro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BuscaRegistro(ByVal cadena As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/BuscaRegistro", ReplyAction:="*")>  _
        Function BuscaRegistroAsync(ByVal cadena As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/NuevoRegistro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function NuevoRegistro(ByVal NOMBRE As String, ByVal TELEFONO As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/NuevoRegistro", ReplyAction:="*")>  _
        Function NuevoRegistroAsync(ByVal NOMBRE As String, ByVal TELEFONO As String) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/ActualizarRegistro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ActualizarRegistro(ByVal ID As Integer, ByVal NOMBRE As String, ByVal TELEFONO As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/ActualizarRegistro", ReplyAction:="*")>  _
        Function ActualizarRegistroAsync(ByVal ID As Integer, ByVal NOMBRE As String, ByVal TELEFONO As String) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/EliminaRegistro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EliminaRegistro(ByVal ID As Integer) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/EliminaRegistro", ReplyAction:="*")>  _
        Function EliminaRegistroAsync(ByVal ID As Integer) As System.Threading.Tasks.Task(Of Object)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface empleadosSoapChannel
        Inherits ServicioDatos.empleadosSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class empleadosSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicioDatos.empleadosSoap)
        Implements ServicioDatos.empleadosSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function BuscaRegistro(ByVal cadena As String) As System.Data.DataSet Implements ServicioDatos.empleadosSoap.BuscaRegistro
            Return MyBase.Channel.BuscaRegistro(cadena)
        End Function
        
        Public Function BuscaRegistroAsync(ByVal cadena As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServicioDatos.empleadosSoap.BuscaRegistroAsync
            Return MyBase.Channel.BuscaRegistroAsync(cadena)
        End Function
        
        Public Function NuevoRegistro(ByVal NOMBRE As String, ByVal TELEFONO As String) As Object Implements ServicioDatos.empleadosSoap.NuevoRegistro
            Return MyBase.Channel.NuevoRegistro(NOMBRE, TELEFONO)
        End Function
        
        Public Function NuevoRegistroAsync(ByVal NOMBRE As String, ByVal TELEFONO As String) As System.Threading.Tasks.Task(Of Object) Implements ServicioDatos.empleadosSoap.NuevoRegistroAsync
            Return MyBase.Channel.NuevoRegistroAsync(NOMBRE, TELEFONO)
        End Function
        
        Public Function ActualizarRegistro(ByVal ID As Integer, ByVal NOMBRE As String, ByVal TELEFONO As String) As Object Implements ServicioDatos.empleadosSoap.ActualizarRegistro
            Return MyBase.Channel.ActualizarRegistro(ID, NOMBRE, TELEFONO)
        End Function
        
        Public Function ActualizarRegistroAsync(ByVal ID As Integer, ByVal NOMBRE As String, ByVal TELEFONO As String) As System.Threading.Tasks.Task(Of Object) Implements ServicioDatos.empleadosSoap.ActualizarRegistroAsync
            Return MyBase.Channel.ActualizarRegistroAsync(ID, NOMBRE, TELEFONO)
        End Function
        
        Public Function EliminaRegistro(ByVal ID As Integer) As Object Implements ServicioDatos.empleadosSoap.EliminaRegistro
            Return MyBase.Channel.EliminaRegistro(ID)
        End Function
        
        Public Function EliminaRegistroAsync(ByVal ID As Integer) As System.Threading.Tasks.Task(Of Object) Implements ServicioDatos.empleadosSoap.EliminaRegistroAsync
            Return MyBase.Channel.EliminaRegistroAsync(ID)
        End Function
    End Class
End Namespace
